import Navbar from '@/components/Navbar';
import Head from 'next/head';
import Banner from '@/components/Banner';
import About from '@/components/About';
import Experience from '@/components/Experience';
import Projects from '@/components/Projects';
import Archive from '@/components/Archive';
import Contact from '@/components/Contact';
import Footer from '@/components/Footer';

export default function Home() {
	return (
		<>
			<Head>
				<title>Aakash Hadli | Web Developer </title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/logo1.ico' />
			</Head>
			<main className='w-full h-screen font-bodyFont bg-bodyColor text-textLight overflow-x-hidden overflow-y-scroll scrollbar-none'>
				<Navbar />
				<div className='w-full h-[100vh] xl:flex items-center gap-20 justify-between'>
					<div className='h-[100vh] w-full mx-auto p-4'>
						<Banner />
						<About />
						<Experience />
						<Projects />
						<Archive />
						<Contact />
						<Footer />
					</div>
				</div>
			</main>
		</>
	);
}
